# Generated by Django 4.2.11 on 2024-05-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0018_alter_menu_moment_alter_menu_nbr_anim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.CreateModel(
            name="IngredientXSU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=20,
                        verbose_name="Quantité",
                    ),
                ),
                ("su", models.BooleanField(default=False, verbose_name="SU ?")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="database.category",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="database.ingredient",
                    ),
                ),
            ],
        ),
    ]
