# Generated by Django 4.2.11 on 2024-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0020_alter_recipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.TextField(verbose_name="Nom"),
        ),
    ]
